# Generated by Django 5.1.6 on 2025-02-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(blank=True, default=1, max_length=20),
            preserve_default=False,
        ),
    ]
