# Generated by Django 5.1.6 on 2025-02-12 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="linked_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="secondary_contacts",
                to="api.contact",
            ),
        ),
    ]
